dist: xenial
sudo: required
services:
  - docker
language: go
go:
  - "1.11.x"

before_install:
# locally: docker run -it ubuntu:16.04 bash
- sudo apt-get update
- sudo apt-get -y install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y install docker-ce=5:18.09.6~3-0~ubuntu-xenial
- docker version

install:
# This script is used by the Travis build to install a cookie for
# go.googlesource.com so rate limits are higher when using `go get` to fetch
# packages that live there.
# See: https://github.com/golang/go/issues/12933
- bash scripts/gogetcookie.sh
- sudo sed 's/DOCKER_OPTS="/DOCKER_OPTS="--insecure-registry=127.0.0.1:15000 /g' -i /etc/default/docker
- sudo cat /etc/default/docker
- sudo service docker restart

script:
- make vet
- make test
- make testacc
#- make compile
#- make website-test

branches:
  only:
  - master
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
env:
  - GOFLAGS=-mod=vendor GO111MODULE=on
